[package]
name = "RSS-Bot-Telegram"
version = "0.1.0"
authors = ["Bastien <bastien@example.com>"]
edition = "2018"

[build-dependencies]
ctl10n = "0.2.0"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
rss = "1.10"
chrono = "0.4"
reqwest = "0.10"
dissolve = "0.2.2"
tbot = "0.6"
